### ISSUE TITLE
Increase the possible length of the password to about 150

### ISSUE THREAD

**Issue by Wjxfi** [polilluminato/wassword-flutter#14]

**Comment by polilluminato** [comment]
Hi @Wjxfi thanks for the feedback. 

why do you want to increase the length of the password so much? Do you have any particular use cases?

In general, the password required in login forms is in the range of 30-40 characters maximum.

I am developing a passphrase creation section (#3), perhaps in contexts where a very long password is required the passphrase can be used, what do you think? 
For convenience I could also add the length of the generated string to the passphrase screen so that the user has evidence of the number of characters.

**Comment by Wjxfi** [comment]
create it however you want. i haven't studied it, so i can't say which is better.
For me I really need such a long password. for file encryption (most important (small passwords are not reliable)), creating special accounts, backups, etc.

**Comment by polilluminato** [comment]
OK I can increase the length of the generated password, I'll do some testing from the UI point of view.

As an example KeepassXC and Bitwarden can generate passwords up to 128 characters, so I think it's a good compromise to go that far.

**Comment by Wjxfi** [comment]
where is the update?

**Comment by polilluminato** [comment]
@Wjxfi The update is on the develop branch, I'll plan to release it in a couple of weeks.
